// Mocks generated by Mockito 5.4.5 from annotations
// in linkedin_clone/test/unit/providers/networks_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:linkedin_clone/features/connections/domain/entities/connections_user_entity.dart'
    as _i6;
import 'package:linkedin_clone/features/connections/domain/entities/people_you_may_know_user_entity.dart'
    as _i15;
import 'package:linkedin_clone/features/connections/domain/repository/connections_repository.dart'
    as _i2;
import 'package:linkedin_clone/features/connections/domain/usecases/follow/follow_user_usecase.dart'
    as _i9;
import 'package:linkedin_clone/features/connections/domain/usecases/follow/get_followers_list_usecase.dart'
    as _i8;
import 'package:linkedin_clone/features/connections/domain/usecases/follow/get_following_list_usecase.dart'
    as _i4;
import 'package:linkedin_clone/features/connections/domain/usecases/follow/unfollow_user_usecase.dart'
    as _i7;
import 'package:linkedin_clone/features/connections/domain/usecases/get_people_you_may_know_usecase.dart'
    as _i14;
import 'package:linkedin_clone/features/privacy/domain/entities/privacy_user_entity.dart'
    as _i11;
import 'package:linkedin_clone/features/privacy/domain/repository/privacy_repository.dart'
    as _i3;
import 'package:linkedin_clone/features/privacy/domain/usecases/block_user_usecase.dart'
    as _i12;
import 'package:linkedin_clone/features/privacy/domain/usecases/get_blocked_list_usecase.dart'
    as _i10;
import 'package:linkedin_clone/features/privacy/domain/usecases/unblock_user_usecase.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConnectionsRepository_0 extends _i1.SmartFake
    implements _i2.ConnectionsRepository {
  _FakeConnectionsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrivacyRepository_1 extends _i1.SmartFake
    implements _i3.PrivacyRepository {
  _FakePrivacyRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFollowingListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFollowingListUseCase extends _i1.Mock
    implements _i4.GetFollowingListUseCase {
  MockGetFollowingListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConnectionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConnectionsRepository);

  @override
  _i5.Future<List<_i6.ConnectionsUserEntity>> call({
    int? page = 0,
    int? limit = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i6.ConnectionsUserEntity>>.value(
              <_i6.ConnectionsUserEntity>[],
            ),
          )
          as _i5.Future<List<_i6.ConnectionsUserEntity>>);
}

/// A class which mocks [UnfollowUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnfollowUserUseCase extends _i1.Mock
    implements _i7.UnfollowUserUseCase {
  MockUnfollowUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConnectionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConnectionsRepository);

  @override
  _i5.Future<bool> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GetFollowersListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFollowersListUseCase extends _i1.Mock
    implements _i8.GetFollowersListUseCase {
  MockGetFollowersListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConnectionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConnectionsRepository);

  @override
  _i5.Future<List<_i6.ConnectionsUserEntity>> call({
    int? page = 0,
    int? limit = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i6.ConnectionsUserEntity>>.value(
              <_i6.ConnectionsUserEntity>[],
            ),
          )
          as _i5.Future<List<_i6.ConnectionsUserEntity>>);
}

/// A class which mocks [FollowUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowUserUseCase extends _i1.Mock implements _i9.FollowUserUseCase {
  MockFollowUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConnectionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConnectionsRepository);

  @override
  _i5.Future<bool> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GetBlockedListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBlockedListUseCase extends _i1.Mock
    implements _i10.GetBlockedListUseCase {
  MockGetBlockedListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PrivacyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrivacyRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PrivacyRepository);

  @override
  _i5.Future<List<_i11.PrivacyUserEntity>> call({
    int? page = 0,
    int? limit = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i11.PrivacyUserEntity>>.value(
              <_i11.PrivacyUserEntity>[],
            ),
          )
          as _i5.Future<List<_i11.PrivacyUserEntity>>);
}

/// A class which mocks [BlockUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockUserUseCase extends _i1.Mock implements _i12.BlockUserUseCase {
  MockBlockUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PrivacyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrivacyRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PrivacyRepository);

  @override
  _i5.Future<bool> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [UnblockUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnblockUserUseCase extends _i1.Mock
    implements _i13.UnblockUserUseCase {
  MockUnblockUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PrivacyRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrivacyRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PrivacyRepository);

  @override
  _i5.Future<bool> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GetPeopleYouMayKnowUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPeopleYouMayKnowUseCase extends _i1.Mock
    implements _i14.GetPeopleYouMayKnowUseCase {
  MockGetPeopleYouMayKnowUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConnectionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConnectionsRepository);

  @override
  _i5.Future<List<_i15.PeopleYouMayKnowUserEntity>> call({
    int? page = 0,
    int? limit = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue:
                _i5.Future<List<_i15.PeopleYouMayKnowUserEntity>>.value(
                  <_i15.PeopleYouMayKnowUserEntity>[],
                ),
          )
          as _i5.Future<List<_i15.PeopleYouMayKnowUserEntity>>);
}
