// Mocks generated by Mockito 5.4.5 from annotations
// in linkedin_clone/test/unit/providers/premium_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:linkedin_clone/features/premium/domain/repository/premium_repository.dart'
    as _i2;
import 'package:linkedin_clone/features/premium/domain/usecases/cancel_use_case.dart'
    as _i5;
import 'package:linkedin_clone/features/premium/domain/usecases/subscribe_to_premium_plan_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePremiumRepository_0 extends _i1.SmartFake
    implements _i2.PremiumRepository {
  _FakePremiumRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscribeToPremiumPlanUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscribeToPremiumPlanUseCase extends _i1.Mock
    implements _i3.SubscribeToPremiumPlanUseCase {
  MockSubscribeToPremiumPlanUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PremiumRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePremiumRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PremiumRepository);

  @override
  _i4.Future<String?> call(bool? isYearly, bool? autoRenewal) =>
      (super.noSuchMethod(
            Invocation.method(#call, [isYearly, autoRenewal]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [CancelUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelUseCase extends _i1.Mock implements _i5.CancelUseCase {
  MockCancelUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PremiumRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePremiumRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PremiumRepository);

  @override
  _i4.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
