name: linkedin_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  timeago: ^3.0.2
  fpdart: ^1.1.1
  dartz: ^0.10.0
  flutter_bloc: ^7.3.0
  provider: ^6.1.1
  http: ^1.3.0
  go_router: ^14.8.1
  google_sign_in: ^6.1.0
  equatable: ^2.0.5
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  shared_preferences: ^2.1.1
  webview_flutter_plus: ^0.4.7
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^10.8.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  url_launcher: ^6.1.5
  dropdown_button2: ^2.3.9
  mockito: ^5.4.2
  build_runner: ^2.4.4
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  dartz: ^0.10.1 # For Either type handling
  test: ^1.24.0 # Core testing package

flutter:
  uses-material-design: true
  assets:
    - assets/images/linkedin_logo.png
    - assets/images/onboarding_illustration.jpg
    - assets/html/recaptcha.html
    - assets/images/profile.png  #TODO: remove this line after connecting to API
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
