// Mocks generated by Mockito 5.4.5 from annotations
// in linkedin_clone/test/presentation/saved_jobs_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:linkedin_clone/features/company/domain/entities/create_job_entity.dart'
    as _i5;
import 'package:linkedin_clone/features/jobs/domain/entities/application_entity.dart'
    as _i7;
import 'package:linkedin_clone/features/jobs/domain/entities/apply_for_job_entity.dart'
    as _i6;
import 'package:linkedin_clone/features/jobs/domain/entities/job_entity.dart'
    as _i2;
import 'package:linkedin_clone/features/jobs/domain/repositories/job_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJob_0 extends _i1.SmartFake implements _i2.Job {
  _FakeJob_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JobRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobRepository extends _i1.Mock implements _i3.JobRepository {
  MockJobRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Job>> getRecentJobs(
    String? companyId, {
    int? page = 1,
    int? limit = 4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecentJobs,
              [companyId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<List<_i2.Job>>.value(<_i2.Job>[]),
          )
          as _i4.Future<List<_i2.Job>>);

  @override
  _i4.Future<bool> addJob(_i5.CreateJobEntity? job, String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#addJob, [job, companyId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Job>> searchJobs({
    String? keyword,
    String? location,
    String? industry,
    String? experienceLevel,
    String? company,
    double? minSalary,
    double? maxSalary,
    int? page = 1,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchJobs, [], {
              #keyword: keyword,
              #location: location,
              #industry: industry,
              #experienceLevel: experienceLevel,
              #company: company,
              #minSalary: minSalary,
              #maxSalary: maxSalary,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Job>>.value(<_i2.Job>[]),
          )
          as _i4.Future<List<_i2.Job>>);

  @override
  _i4.Future<bool> deleteJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJob, [jobId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> applyForJob(_i6.ApplyForJobEntity? application) =>
      (super.noSuchMethod(
            Invocation.method(#applyForJob, [application]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.ApplicationEntity>> getApplicants(
    String? jobId, {
    int? page = 1,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getApplicants,
              [jobId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<List<_i7.ApplicationEntity>>.value(
              <_i7.ApplicationEntity>[],
            ),
          )
          as _i4.Future<List<_i7.ApplicationEntity>>);

  @override
  _i4.Future<bool> updateApplicationStatus(
    String? applicationId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateApplicationStatus, [
              applicationId,
              newStatus,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> saveJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#saveJob, [jobId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> unsaveJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#unsaveJob, [jobId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Job> getJobById(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobById, [jobId]),
            returnValue: _i4.Future<_i2.Job>.value(
              _FakeJob_0(this, Invocation.method(#getJobById, [jobId])),
            ),
          )
          as _i4.Future<_i2.Job>);
}
